FROM maven:3.9-eclipse-temurin-21 AS build
COPY . /app
WORKDIR /app
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre

RUN apt-get update && apt-get install -y \
    xvfb \
    x11vnc \
    fluxbox \
    python3-websockify \
    supervisor \
    wget \
    && wget -qO /tmp/novnc.tar.gz https://github.com/novnc/noVNC/archive/refs/tags/v1.4.0.tar.gz \
    && tar -xzf /tmp/novnc.tar.gz -C /opt \
    && mv /opt/noVNC-1.4.0 /opt/novnc \
    && rm /tmp/novnc.tar.gz \
    && rm -rf /var/lib/apt/lists/*

ENV DISPLAY=:99
ENV START_MODE=gui

WORKDIR /app
COPY --from=build /app/target/someone-1.0-SNAPSHOT.jar /app/app.jar
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 6080 5900 8081

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]