services:
  db:
    image: mysql:8.3
    container_name: library_db_gui_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 74542474
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - db_data_gui:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p74542474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app-gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    container_name: library_app_gui_container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6080:6080"  # noVNC Web Interface (Open http://localhost:6080 in browser)
      - "5900:5900"  # Raw VNC connection (optional)
      - "8081:8081"  # Embed web server port (if used)
    environment:
      - DB_URL=jdbc:mysql://db:3306/
      - DB_USER=root
      - DB_PASSWORD=74542474
      - DB_NAME=library_db
      - START_MODE=gui
    restart: on-failure

volumes:
  db_data_gui:
