[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=Xvfb :99 -screen 0 1280x800x24 -listen tcp -ac
autorestart=true
priority=10

[program:fluxbox]
command=fluxbox
environment=DISPLAY=:99
autorestart=true
priority=20

[program:x11vnc]
command=x11vnc -shared -forever -nopw -display :99
autorestart=true
priority=30

[program:novnc]
command=websockify --web /usr/share/novnc 6080 localhost:5900
autorestart=true
priority=40

[program:java-gui]
command=java -cp app.jar org.example.Main
environment=DISPLAY=:99,START_MODE=gui,DB_URL="jdbc:mysql://db:3306/",DB_USER="root",DB_PASSWORD="74542474",DB_NAME="library_db"
directory=/app
autorestart=true
priority=50
