google.api.key=${GOOGLE_API_KEY:}
http.timeout=10
http.max.retries=3
cache.dir=${user.home}/.someone/cache

# MySQL Connection properties
db.url=jdbc:mysql://localhost:3306/
db.name=library_db
db.user=root
db.password=74542474

# Storage (???????, ??? ??? ????? ???????? ? ??)
# storage.path=storage
